"""add preset models

Revision ID: 21c190be64f1
Revises: b20fc7cc0496
Create Date: 2026-02-22 15:53:50.980202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c190be64f1'
down_revision: Union[str, None] = 'b20fc7cc0496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severities', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('severities', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_presets_user_id'), 'user_presets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_presets_user_id'), table_name='user_presets')
    op.drop_table('user_presets')
    op.drop_table('enterprise_presets')
    # ### end Alembic commands ###
