"""add auth models

Revision ID: b20fc7cc0496
Revises: 8b7f0537afe6
Create Date: 2026-02-22 15:32:39.255293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b20fc7cc0496'
down_revision: Union[str, None] = '8b7f0537afe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ad_group_dn', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('ad_domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('hosts', 'first_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('hosts_ip_key', 'hosts', type_='unique')
    op.drop_index('ix_hosts_ip', table_name='hosts')
    op.create_index(op.f('ix_hosts_ip'), 'hosts', ['ip'], unique=True)
    op.alter_column('import_jobs', 'progress',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('import_jobs', 'rows_processed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('import_jobs', 'rows_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('report_coherence_checks', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scan_reports', 'imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scan_reports', 'imported_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('report_coherence_checks', 'detected_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_jobs', 'rows_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('import_jobs', 'rows_processed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('import_jobs', 'progress',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_hosts_ip'), table_name='hosts')
    op.create_index('ix_hosts_ip', 'hosts', ['ip'], unique=False)
    op.create_unique_constraint('hosts_ip_key', 'hosts', ['ip'])
    op.alter_column('hosts', 'last_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('hosts', 'first_seen',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('profiles')
    # ### end Alembic commands ###
